### ISSUE TITLE
copy pasta

### ISSUE THREAD

**Issue by Jaehdawg** [sThig/drum-kit#1]
http://telsaiori.blogspot.com/2016/12/javascript-drum-kit-javascript30.html

What did you learn here?

**Comment by sThig** [comment]
got the copy pasta, in future projects going ahead I'll do a TIL instead, please pardon my progress ;)

On this project I learned more about how to affect data attributes (he, Wes Bos, went into detail about that, how they came about and how they got structured into today's coding).  

Given ES6 is newer to me, I learned about the syntax such as 
`.key[data-key="${e.keyCode}"]`

 for example (using the back tic).  

Also, since I'm going to push all these projects to github, it'll help me make this second nature too.

**Comment by Jaehdawg** [comment]
Nothing is wrong with copy/pasta.  But I want to make sure you understand what is happening with these what this demo is trying to teach you.  The demo is showing you how you can take physical input and map it to perform specific actions like playing a sound file.  This is exactly that I was trying to explain to you on your demo that you created for Partnerships.  Map a keyboard or mouse clicker event to a move a slide.
